#!/bin/bash

echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"

echo "Please Select your path "

likedirectory=Y

read -p "Do you like search this directory? [Y/n] " likedirectory

#***********************
if [[ "$likedirectory" == "N" || "$likedirectory" == "n" ]]; then
    read -p "enter a directory: " -i "$ROOT/" -e addressdirectory 

    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"

    read -p "Please enter the name of music wich you search : " name

    read -p "Please Select your type d {directory} f {file} : " liketype

    if [[ $liketype == "d" ]]; then

        find $addressdirectory -type d -iname $name

    elif [[ $liketype == "f" ]]; then

        echo "Install the mplayer if you want tp play music after find it"

        find $addressdirectory -type f -iname "*$name*" -exec mplayer {} \;

    else

        echo " your type is not true"
    fi
    echo "done!"
#***********************
else
    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"

    read -p "Please enter the name of music wich you search : " name

    read -p "Please Select your type d {directory} f {file} : " typelike

    if [[ $typelike == "d" ]]; then

        find  $PWD -type d -name  $name

    elif [[ $typelike == "f" ]]; then

        echo "Install the mplayer if you want tp play music after find it"
 
        find  $PWD -type f -name "*$name*" -exec mplayer {} \;

        echo " your type is not true"

    fi
    echo "done!"
fi
