#!/usr/bin/env bash

function find_check_play()
{
  if [[ $liketype == "d" ]]; then
      find $addressdirectory -type d -iname $name
  elif [[ $liketype == "f" ]]; then
      echo "Install the mplayer if you want tp play music after find it"
      find $addressdirectory -type f -iname "*$name*" -exec mplayer {} \;
  else
      echo " your type is not true"
  fi

}

function input_format()
{
      read -p "Please enter the name of music wich you search : " name
      read -p "Please Select your type d {directory} f {file} : " liketype
}

echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"
echo "Please Select your path "

likedirectory=Y

read -p "Do you like search this directory? [Y/n] " likedirectory

#***********************
if [[ "$likedirectory" == "N" || "$likedirectory" == "n" ]]; then
    read -p "enter a directory: " -i "$ROOT/" -e addressdirectory 

    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"

    input_format addressdirectory

    find_check_play liketype
    find_check_play name

    echo "done!"
#***********************
else
    echo "-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/"

    input_format addressdirectory

    find_check_play liketype
    find_check_play name    
    echo "done!"
fi
